Retrying test on specific exceptions
junit-pioneer/junit-pioneer pull request #504
Opened 2021-07-25 12:12 UTC by nipafx

---
**PR checklist**

The following checklist shall help the PR's author, the reviewers and maintainers to ensure the quality of this project.
It is based on our contributors guidelines, especially the ["writing code" section](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#writing-code).
It shall help to check for completion of the listed points.
If a point does not apply to the given PR's changes, the corresponding entry can be simply marked as done. 

Documentation (general)
* [ ] There is documentation (Javadoc and site documentation; added or updated)
* [x] There is implementation information to describe _why_ a non-obvious source code / solution got implemented
* [x] Site documentation has its own `.adoc` file in the `docs` folder, e.g. `docs/report-entries.adoc`
* [x] Only one sentence per line (especially in `.adoc` files)
* [x] Javadoc uses formal style, while sites documentation may use informal style

Documentation (new extension)
* [x] The `docs/docs-nav.yml` navigation has an entry for the new extension
* [x] The `package-info.java` contains information about the new extension

Code
* [x] Code adheres to code style, naming conventions etc.
* [x] Successful tests cover all changes
* [x] There are checks which validate correct / false usage / configuration of a functionality and there are tests to verify those checks
* [x] Tests use [AssertJ](https://assertj.github.io/doc/) or our own [PioneerAssert](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#assertions) (which are based on AssertJ)

Contributing
* [ ] A prepared commit message exists
* [x] The list of contributions inside `README.md` mentions the new contribution (real name optional) 

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

2021-07-25 12:19 UTC, nipafx commented
TODO:

* name for `onExceptions` - what do you think about it?
* website documentation
* commit message

2021-07-27 19:20 UTC, beatngu13 commented on src/main/java/org/junitpioneer/jupiter/RetryingTestExtension.java
> +			return Stream.of(expectedExceptions).anyMatch(type -> type.isInstance(exception));
Personally, I find `Arrays#stream(...)` more readable as it emphasizes that possibly multiple values are given (even if `expectedExceptions` already uses  plural).

2021-07-27 19:22 UTC, nipafx commented
Proposed commit message:

```
Allow retrying tests only on specific exceptions (#406 / #504)

Add new optional attribute `onExceptions` to `@RetryingTest`. If it's present,
the annotated test will only be retried if one of the listed exceptions is
thrown. Otherwise it will fail as if without `@RetryingTest`.

Closes: #406
PR: #504
```

2021-07-27 20:26 UTC, beatngu13 requested changes

2021-07-27 20:26 UTC, beatngu13 commented on src/main/java/org/junitpioneer/jupiter/RetryingTest.java
> + * exceptions, use {@link RetryingTest#onExceptions() onExceptions()}.</p>
```suggestion
 * exceptions, use {@link RetryingTest#onExceptions()}.</p>
```

2021-07-27 20:26 UTC, beatngu13 commented on src/test/java/org/junitpioneer/jupiter/RetryingTestExtensionTests.java
> +			EXECUTION_COUNT++;
I know it was there before, but why is execution count upper camel case? It's not a constant?

2021-07-27 20:26 UTC, beatngu13 commented on src/test/java/org/junitpioneer/jupiter/RetryingTestExtensionTests.java
> +		assertThat(results).hasNumberOfDynamicallyRegisteredTests(1).hasNumberOfFailedTests(1);
```suggestion
		assertThat(results)
				.hasNumberOfDynamicallyRegisteredTests(1)
				.hasNumberOfFailedTests(1);
```

2021-07-27 20:26 UTC, beatngu13 commented on src/test/java/org/junitpioneer/jupiter/RetryingTestExtensionTests.java
> +		assertThat(results).hasNumberOfDynamicallyRegisteredTests(2).hasNumberOfAbortedTests(2);
```suggestion
		assertThat(results)
				.hasNumberOfDynamicallyRegisteredTests(2)
				.hasNumberOfAbortedTests(2);
```

2021-07-27 20:26 UTC, beatngu13 commented on src/test/java/org/junitpioneer/jupiter/RetryingTestExtensionTests.java
> +				Assumptions.assumeFalse(true);
Since we refer to this specific exception in our code and docs?

```suggestion
				throw new TestAbortedException();
```

2021-07-27 20:38 UTC, nipafx commented on src/main/java/org/junitpioneer/jupiter/RetryingTest.java
> + * exceptions, use {@link RetryingTest#onExceptions() onExceptions()}.</p>
I like it better that way. 😁

2021-07-27 20:41 UTC, nipafx commented on src/test/java/org/junitpioneer/jupiter/RetryingTestExtensionTests.java
> +		assertThat(results).hasNumberOfDynamicallyRegisteredTests(2).hasNumberOfAbortedTests(2);
Spotless doesn't let us have nice things.

2021-07-27 20:41 UTC, nipafx commented on src/test/java/org/junitpioneer/jupiter/RetryingTestExtensionTests.java
> +		assertThat(results).hasNumberOfDynamicallyRegisteredTests(1).hasNumberOfFailedTests(1);
Spotless doesn't let us have nice things.

2021-08-01 17:14 UTC, Bukama approved these changes
Seems good to me - and the UPPERCASE "constant" went lowercase variable 👍

2021-08-09 20:48 UTC, beatngu13 approved these changes

2021-09-02 19:58 UTC, merged