Cleanup jupiter's package-info (#554)
junit-pioneer/junit-pioneer pull request #556
Opened 2021-12-12 13:36 UTC by Bukama

Proposed commit message:

```
Updates the package-info.java of the org.junitpioneer.jupiter package,
removing old / non-public classes and adding not listed subpackages.

#closes: #554
#PR:
```

---

I hereby agree to the terms of the [JUnit Pioneer Contributor License Agreement](https://github.com/junit-pioneer/junit-pioneer/blob/main/CONTRIBUTING.md#junit-pioneer-contributor-license-agreement).

2021-12-12 13:52 UTC, Bukama commented
Marking the `NullEnum` as deprecated in this PR too as @Michael1993 confirmed it belongs too the old CartesianProductExtension and I think a PR for this single update would be overkill if I'm already there polishing the package-info file for that package.

2021-12-12 20:52 UTC, beatngu13 requested changes
Regarding the proposed commit message, I would suggest:

```text
Update package info

Updates the `package-info.java` of the `org.junitpioneer.jupiter` package,
removing old / non-public classes and adding not listed "subpackages".

Closes: #554
PR: #556
```

2021-12-12 20:52 UTC, beatngu13 commented on src/main/java/org/junitpioneer/jupiter/NullEnum.java
> +@Deprecated
The corresponding `@deprecated` Javadoc tag is missing:

https://sonarcloud.io/project/issues?id=junit-pioneer_junit-pioneer&open=AX2u626WwakKrVHzG7jF&pullRequest=556&resolved=false&types=CODE_SMELL

2021-12-12 20:52 UTC, beatngu13 commented on src/main/java/org/junitpioneer/jupiter/package-info.java
> + * Also check the following subpackages:
Since there are no "subpackages", I would suggest:

```suggestion
 * Also check the following packages:
```

2021-12-19 13:49 UTC, beatngu13 approved these changes
Thx for adopting my suggestions.

What bugs me:

https://sonarcloud.io/project/issues?id=junit-pioneer_junit-pioneer&open=AX2u626WwakKrVHzG7jE&pullRequest=556&resolved=false&types=CODE_SMELL

Why is _this_ a code smell? I also tried "confirming" it, which says:

>This issue has been reviewed and something should be done eventually to handle it.

I mean, we could resolve (e.g. as false positive), but I wonder what's the "Sonar way" of dealing with this. Marking things as deprecated shouldn't be a code smell IMO.

2021-12-19 20:51 UTC, Bukama commented
Yeah also saw this SonarQube and just laughed, cause I had the exact same thought as you.

2021-12-23 16:29 UTC, nipafx commented
I deactivated the rule "Deprecated code should be removed" and tried to trigger a rerun of the Sonar build but that doesn't seem to work, so I'll just merge anyway.

2021-12-23 16:30 UTC, merged